# Copyright (c) 2025 Environmental Systems Research Institute, Inc.
# SPDX-License-Identifier: Apache-2.0

cmake_minimum_required(VERSION 3.29.2)

project(
  lwyi
  DESCRIPTION "Link what you include"
  LANGUAGES CXX 
  )

################################################################################
## settings

include(CTest)
include(CMakeDependentOption)
include(GNUInstallDirs)

cmake_dependent_option(ENABLE_DOGFOODING "Enable support for running link-what-you-include on itself" ON BUILD_TESTING OFF)

set(CMAKE_CXX_STANDARD 23)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
set(CMAKE_CXX_EXTENSIONS OFF)
set(CMAKE_CXX_SCAN_FOR_MODULES OFF)
set(CMAKE_VERIFY_INTERFACE_HEADER_SETS ON)

if(CMAKE_CXX_COMPILER_ID MATCHES "Clang|GNU")
  add_compile_options(
    -Wall
    -Wextra
    -Wpedantic
    -Wimplicit-fallthrough
    )
endif()

option(ENABLE_CLANG_TIDY "Run clang-tidy while building" FALSE)
if(ENABLE_CLANG_TIDY)
  include(cmake/clang_tidy_support.cmake)
  clang_tidy_support()
endif()

################################################################################
## configure build tree to mirror install tree

if(IS_ABSOLUTE ${CMAKE_INSTALL_BINDIR})
  message(FATAL_ERROR "An absolute path for CMAKE_INSTALL_BINDIR is not supported")
endif()

get_property(is_multi_config GLOBAL PROPERTY GENERATOR_IS_MULTI_CONFIG)
if(is_multi_config)
  set(CMAKE_RUNTIME_OUTPUT_DIRECTORY ${CMAKE_BINARY_DIR}/${CMAKE_INSTALL_BINDIR}_$<LOWER_CASE:$<CONFIG>>)
else()
  set(CMAKE_RUNTIME_OUTPUT_DIRECTORY ${CMAKE_BINARY_DIR}/${CMAKE_INSTALL_BINDIR})
endif()

################################################################################
## dependencies

enable_language(C) # needed for clang
find_package(Clang 18.1 REQUIRED)
target_include_directories(clangTooling SYSTEM INTERFACE ${CLANG_INCLUDE_DIRS})
if (MSVC)
  target_compile_options(clangTooling INTERFACE /GR-)
else()
  target_compile_options(clangTooling INTERFACE -fno-rtti)
endif()

# Upstream simdjson only guarantees releases with the same major and minor versions are compatible.
# Our testing shows that we can use older versions so we work around this restriction here to allow
# the latest version (currently 4.6) and the version available on Ubuntu-26 (4.2).
find_package(simdjson 4.6 QUIET)
if(NOT simdjson_FOUND)
  find_package(simdjson 4.2 QUIET)
endif()
if(simdjson_FOUND)
  message(STATUS "Found simdjson: ${simdjson_VERSION}")
else()
  message(FATAL_ERROR "Failed to find simdjson version 4.2 or 4.6.")
endif()

if(BUILD_TESTING)
  find_package(Catch2 3.7 REQUIRED)
  include(Catch)
endif()

if(ENABLE_DOGFOODING)
  set(link_what_you_include_DIR ${CMAKE_CURRENT_SOURCE_DIR}/cmake)
  find_package(link_what_you_include REQUIRED)

  # Teach CMake about headers for our imported targets
  # Note, this should ideally be done by the upstream package
  get_target_property(simdjson_include simdjson::simdjson INTERFACE_INCLUDE_DIRECTORIES)
  target_sources(simdjson::simdjson
    INTERFACE
    FILE_SET HEADERS
    BASE_DIRS ${simdjson_include}
    FILES ${simdjson_include}/simdjson.h
  )
  set_target_properties(simdjson::simdjson PROPERTIES SYSTEM TRUE)
  get_target_property(clang_include clangTooling INTERFACE_INCLUDE_DIRECTORIES)
  target_sources(clangTooling
    INTERFACE
    FILE_SET HEADERS
    BASE_DIRS ${clang_include}
  )
  set_target_properties(clangTooling PROPERTIES SYSTEM TRUE)
  get_target_property(catch_include Catch2::Catch2 INTERFACE_INCLUDE_DIRECTORIES)
  target_sources(Catch2::Catch2WithMain
    INTERFACE
    FILE_SET HEADERS
    BASE_DIRS ${catch_include}
  )
  set_target_properties(Catch2::Catch2WithMain PROPERTIES SYSTEM TRUE)
endif()

################################################################################
## subdirectories

add_subdirectory(lib/cli)
add_subdirectory(lib/message)
add_subdirectory(lib/lwyi)
add_subdirectory(lib/scanner)
add_subdirectory(lib/target_model)
add_subdirectory(lib/tidy)
add_subdirectory(lib/util)
add_subdirectory(app)

################################################################################
## install cmake support script

install(FILES cmake/link_what_you_include-config.cmake DESTINATION ${CMAKE_INSTALL_DATADIR}/lwyi)
